// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhIwvOGOZGPJddExPqDeUSikTk2_Soeg',
    appId: '1:782627151951:web:65e95a1608cec1175dca3a',
    messagingSenderId: '782627151951',
    projectId: 'be-and-to-be-664c6',
    authDomain: 'be-and-to-be-664c6.firebaseapp.com',
    storageBucket: 'be-and-to-be-664c6.firebasestorage.app',
    measurementId: 'G-C61XYZBPT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABk4fSiYtA7zpr7YUKrj6tDuA0xY5L8R8',
    appId: '1:782627151951:android:ff15096d3210369e5dca3a',
    messagingSenderId: '782627151951',
    projectId: 'be-and-to-be-664c6',
    storageBucket: 'be-and-to-be-664c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMGn1sfjBXjazMjLIIyWmu_VEpZLHbRU',
    appId: '1:782627151951:ios:1d51cbe51606fc585dca3a',
    messagingSenderId: '782627151951',
    projectId: 'be-and-to-be-664c6',
    storageBucket: 'be-and-to-be-664c6.firebasestorage.app',
    iosBundleId: 'com.example.beAndToBeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMGn1sfjBXjazMjLIIyWmu_VEpZLHbRU',
    appId: '1:782627151951:ios:1d51cbe51606fc585dca3a',
    messagingSenderId: '782627151951',
    projectId: 'be-and-to-be-664c6',
    storageBucket: 'be-and-to-be-664c6.firebasestorage.app',
    iosBundleId: 'com.example.beAndToBeAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvhIwvOGOZGPJddExPqDeUSikTk2_Soeg',
    appId: '1:782627151951:web:90a46831e69fca1a5dca3a',
    messagingSenderId: '782627151951',
    projectId: 'be-and-to-be-664c6',
    authDomain: 'be-and-to-be-664c6.firebaseapp.com',
    storageBucket: 'be-and-to-be-664c6.firebasestorage.app',
    measurementId: 'G-GB9GJS0MRH',
  );
}
